/**
 * Real-style suspension appeal case library.
 * Anonymized composites built from public Seller Forum threads and
 * appeal templates. Intended as a knowledge base sellers can search
 * before drafting their own Plan of Action.
 */

export type AppealCategory =
  | "IP Complaint"
  | "Inauthentic"
  | "Review Manipulation"
  | "Related Account"
  | "Late Shipment"
  | "Restricted Product"
  | "Verification";

export type AppealOutcome = "reinstated" | "partial" | "denied" | "pending";

export type AppealCase = {
  id: string;
  category: AppealCategory;
  marketplace: "Amazon" | "Walmart" | "Shopify";
  title: string;
  summary: string;
  rootCause: string;
  /** Bullet steps the seller actually took. */
  correctiveActions: string[];
  preventiveActions: string[];
  /** Documentation that was attached. */
  documents: string[];
  outcome: AppealOutcome;
  /** Days from suspension to reinstatement. */
  timeToResolveDays: number;
  /** Tags to surface related cases. */
  tags: string[];
};

const CASES_RAW: Omit<AppealCase, "id">[] = [
  // ─── IP Complaint (10) ────────────────────────────────────────────
  { category: "IP Complaint", marketplace: "Amazon", title: "Trademark complaint on private-label kitchen tool",
    summary: "Brand owner filed trademark infringement notice; listing deactivated within 4 hours.",
    rootCause: "Used the brand owner's exact word mark in bullet points to improve search relevance.",
    correctiveActions: ["Removed trademarked term from title and bullets", "Contacted rights owner to request retraction", "Provided supplier authorization letter"],
    preventiveActions: ["Implemented pre-publish brand keyword review", "Added USPTO TESS check to listing SOP"],
    documents: ["USPTO TESS screenshot", "Edited listing copy", "Retraction email from rights owner"],
    outcome: "reinstated", timeToResolveDays: 6, tags: ["trademark", "private-label"] },
  { category: "IP Complaint", marketplace: "Amazon", title: "Copyright complaint over product image",
    summary: "Stock photo used without license triggered DMCA-style complaint from photographer.",
    rootCause: "Image sourced from a free-image site that lacked commercial licensing.",
    correctiveActions: ["Removed infringing image", "Purchased commercial license retroactively", "Replaced with original studio photos"],
    preventiveActions: ["Centralized image library with license metadata", "Required studio photography for all SKUs"],
    documents: ["Shutterstock receipt", "Photographer release", "New image set"],
    outcome: "reinstated", timeToResolveDays: 4, tags: ["copyright", "images"] },
  { category: "IP Complaint", marketplace: "Amazon", title: "Design patent complaint on phone case",
    summary: "Direct competitor asserted design patent; account-level enforcement warning issued.",
    rootCause: "Casing geometry inadvertently mirrored a protected ornamental design.",
    correctiveActions: ["Pulled affected SKU permanently", "Engaged IP attorney for clearance review on remaining catalog"],
    preventiveActions: ["Added design-patent clearance to NPI checklist"],
    documents: ["Attorney clearance memo", "SKU retirement evidence"],
    outcome: "partial", timeToResolveDays: 21, tags: ["design-patent", "electronics"] },
  { category: "IP Complaint", marketplace: "Amazon", title: "Utility patent complaint on cosmetic applicator",
    summary: "Rights owner asserted utility patent over applicator mechanism.",
    rootCause: "Supplier copied a patented mechanism without disclosure.",
    correctiveActions: ["Switched suppliers to non-infringing design", "Destroyed remaining infringing inventory"],
    preventiveActions: ["Added IP indemnification clause to supplier agreements"],
    documents: ["Supplier agreement", "Inventory destruction certificate"],
    outcome: "reinstated", timeToResolveDays: 17, tags: ["utility-patent", "beauty"] },
  { category: "IP Complaint", marketplace: "Walmart", title: "Trademark notice on apparel listing",
    summary: "Walmart Brand Portal complaint over use of celebrity name in title.",
    rootCause: "Listing title used celebrity name as a search keyword.",
    correctiveActions: ["Rewrote title without name", "Submitted clean copy to Brand Portal"],
    preventiveActions: ["Built keyword blocklist of celebrity/brand names"],
    documents: ["Old vs new title", "Brand Portal response"],
    outcome: "reinstated", timeToResolveDays: 3, tags: ["trademark", "apparel"] },
  { category: "IP Complaint", marketplace: "Amazon", title: "Logo trademark complaint on packaging",
    summary: "Logo similarity dispute; account placed under enhanced monitoring.",
    rootCause: "OEM packaging carried a logo similar to an established brand.",
    correctiveActions: ["Redesigned packaging", "Submitted before/after photos in POA"],
    preventiveActions: ["Trademark search before packaging finalization"],
    documents: ["New packaging design", "USPTO search results"],
    outcome: "reinstated", timeToResolveDays: 12, tags: ["packaging", "branding"] },
  { category: "IP Complaint", marketplace: "Amazon", title: "Repeat IP complaint — three strikes",
    summary: "Three separate IP complaints triggered account-level review.",
    rootCause: "No central process to track and resolve complaints individually.",
    correctiveActions: ["Resolved each complaint with rights owner separately", "Submitted consolidated POA addressing all three"],
    preventiveActions: ["Hired dedicated IP coordinator", "Weekly Brand Registry audit"],
    documents: ["Per-complaint retractions", "New SOP"],
    outcome: "reinstated", timeToResolveDays: 28, tags: ["account-level", "process"] },
  { category: "IP Complaint", marketplace: "Shopify", title: "Trademark cease-and-desist to Shopify store",
    summary: "Rights owner contacted Shopify Trust & Safety; store frozen pending response.",
    rootCause: "Product line used a confusingly similar mark.",
    correctiveActions: ["Rebranded product line", "Issued written undertaking to rights owner"],
    preventiveActions: ["Annual trademark audit across catalog"],
    documents: ["Undertaking letter", "Rebranded SKUs"],
    outcome: "reinstated", timeToResolveDays: 9, tags: ["trademark", "rebrand"] },
  { category: "IP Complaint", marketplace: "Amazon", title: "False IP complaint from competitor",
    summary: "Competitor filed bad-faith trademark complaint they did not own.",
    rootCause: "Marketplace enforcement is reactive — complaint accepted at face value.",
    correctiveActions: ["Filed counter-notice with proof of brand ownership", "Reported abuse via report-abuse@"],
    preventiveActions: ["Enrolled in Brand Registry for future protection"],
    documents: ["USPTO registration", "Counter-notice", "Abuse report ID"],
    outcome: "reinstated", timeToResolveDays: 5, tags: ["abuse", "counter-notice"] },
  { category: "IP Complaint", marketplace: "Amazon", title: "Image-only IP complaint after photo edit",
    summary: "Rights owner objected to manipulated product photo on listing.",
    rootCause: "Photo retouching introduced elements suggestive of protected trade dress.",
    correctiveActions: ["Reverted to original product photo", "Documented retouching policy"],
    preventiveActions: ["Approval workflow for image edits"],
    documents: ["Original photo", "Retouching policy doc"],
    outcome: "reinstated", timeToResolveDays: 3, tags: ["trade-dress"] },

  // ─── Inauthentic (10) ─────────────────────────────────────────────
  { category: "Inauthentic", marketplace: "Amazon", title: "Single buyer 'not authentic' complaint",
    summary: "One buyer complaint triggered listing suspension on best-selling ASIN.",
    rootCause: "Buyer received open-box unit due to a warehouse repack.",
    correctiveActions: ["Pulled affected lot for inspection", "Submitted distributor invoices for last 365 days"],
    preventiveActions: ["Sealed-unit verification at FBA prep"],
    documents: ["365-day invoice ledger", "FBA prep SOP"],
    outcome: "reinstated", timeToResolveDays: 8, tags: ["FBA", "prep"] },
  { category: "Inauthentic", marketplace: "Amazon", title: "Authenticity warning on cosmetics",
    summary: "Random authenticity test failed batch verification.",
    rootCause: "Distributor mixed parallel-import lots with domestic stock.",
    correctiveActions: ["Switched to single-source domestic distributor", "Disposed of mixed-lot inventory"],
    preventiveActions: ["Lot-coded receiving with batch traceability"],
    documents: ["New distributor invoice", "Disposal certificate", "Batch QC log"],
    outcome: "reinstated", timeToResolveDays: 14, tags: ["beauty", "diversion"] },
  { category: "Inauthentic", marketplace: "Amazon", title: "Counterfeit complaint on consumer electronics",
    summary: "Multiple buyer complaints over packaging differences.",
    rootCause: "Manufacturer changed packaging mid-production without notice.",
    correctiveActions: ["Obtained manufacturer letter confirming packaging change", "Updated listing images"],
    preventiveActions: ["Manufacturer change-notification clause in PO terms"],
    documents: ["Manufacturer letter", "PO with revision clause"],
    outcome: "reinstated", timeToResolveDays: 11, tags: ["electronics", "packaging"] },
  { category: "Inauthentic", marketplace: "Amazon", title: "Inauthentic claim on collectible toys",
    summary: "Rights owner challenged authenticity of licensed character figures.",
    rootCause: "Wholesale source could not produce chain-of-custody beyond 2 hops.",
    correctiveActions: ["Sourced from authorized distributor only", "Discarded unverifiable inventory"],
    preventiveActions: ["Vendor verification SOP, 2-step minimum"],
    documents: ["Authorized distributor agreement", "Discard report"],
    outcome: "partial", timeToResolveDays: 22, tags: ["toys", "licensed"] },
  { category: "Inauthentic", marketplace: "Amazon", title: "Used-as-new complaint on appliances",
    summary: "Buyer reported receiving a product with signs of prior use.",
    rootCause: "Returns were being relisted as new without QC.",
    correctiveActions: ["Stopped relisting customer returns as new", "Refunded affected buyers proactively"],
    preventiveActions: ["Returns-to-Used reclassification workflow"],
    documents: ["Returns SOP", "Buyer refund evidence"],
    outcome: "reinstated", timeToResolveDays: 7, tags: ["returns", "appliances"] },
  { category: "Inauthentic", marketplace: "Amazon", title: "Authenticity on supplements",
    summary: "FDA-related authenticity flag on supplements with off-spec labeling.",
    rootCause: "Bilingual label printed with US ingredients order on the non-US side.",
    correctiveActions: ["Relabeled inventory", "Submitted COA and lab tests"],
    preventiveActions: ["Label review with compliance contractor"],
    documents: ["COA", "Lab tests", "New label proof"],
    outcome: "reinstated", timeToResolveDays: 18, tags: ["supplements", "labeling"] },
  { category: "Inauthentic", marketplace: "Walmart", title: "Walmart authenticity hold on apparel",
    summary: "Walmart Trust & Safety held disbursements pending source verification.",
    rootCause: "Brand registry required for category recently expanded.",
    correctiveActions: ["Submitted brand authorization", "Enrolled in Walmart Brand Portal"],
    preventiveActions: ["Brand registry review for each new category"],
    documents: ["Brand authorization letter", "Brand Portal enrollment"],
    outcome: "reinstated", timeToResolveDays: 13, tags: ["walmart", "apparel"] },
  { category: "Inauthentic", marketplace: "Amazon", title: "Inauthentic on grocery — expiration mismatch",
    summary: "Buyer received product with expiration date earlier than listing claim.",
    rootCause: "FBA pulled older stock first; listing claim was based on newest batch.",
    correctiveActions: ["Removed batch-specific claims from listing", "Pulled near-expiry inventory"],
    preventiveActions: ["FEFO (first-expired-first-out) staging at prep"],
    documents: ["Expiry audit", "Updated listing copy"],
    outcome: "reinstated", timeToResolveDays: 9, tags: ["grocery", "FEFO"] },
  { category: "Inauthentic", marketplace: "Amazon", title: "Inauthentic on private-label with no distributor",
    summary: "Seller could not provide distributor invoice because they own the brand.",
    rootCause: "Amazon's intake template defaulted to 'distributor invoice'.",
    correctiveActions: ["Submitted manufacturing agreement and Brand Registry proof"],
    preventiveActions: ["Pre-built brand-owner POA pack"],
    documents: ["Manufacturing agreement", "Brand Registry certificate"],
    outcome: "reinstated", timeToResolveDays: 6, tags: ["brand-owner"] },
  { category: "Inauthentic", marketplace: "Amazon", title: "Inauthentic — wrong ASIN matched at receive",
    summary: "FBA inbound matched product to a similar-looking ASIN owned by another seller.",
    rootCause: "FNSKU was missing on units; FBA defaulted to barcode match.",
    correctiveActions: ["Filed inventory adjustment", "Re-labeled all units with FNSKU"],
    preventiveActions: ["Mandatory FNSKU labeling at prep"],
    documents: ["Inventory adjustment case ID", "Re-labeling photos"],
    outcome: "reinstated", timeToResolveDays: 10, tags: ["FBA", "FNSKU"] },

  // ─── Review Manipulation (7) ─────────────────────────────────────
  { category: "Review Manipulation", marketplace: "Amazon", title: "Suspected incentivized reviews after Facebook group post",
    summary: "Account suspended after 14 reviews from same Facebook giveaway group.",
    rootCause: "Marketing manager joined a 'review-for-refund' Facebook group.",
    correctiveActions: ["Terminated marketing contractor", "Submitted full marketing channel inventory in POA"],
    preventiveActions: ["Banned third-party review groups in employee contracts"],
    documents: ["Marketing channel list", "Contractor termination"],
    outcome: "reinstated", timeToResolveDays: 16, tags: ["facebook", "incentivized"] },
  { category: "Review Manipulation", marketplace: "Amazon", title: "Review bombing by competitor",
    summary: "Sudden 1-star spike from accounts created same day.",
    rootCause: "Coordinated competitor attack outside seller's control.",
    correctiveActions: ["Reported pattern with screenshots to Amazon", "Used 'Report Abuse' on each suspicious review"],
    preventiveActions: ["Daily review-pattern monitoring"],
    documents: ["Review IDs", "Screenshots", "Abuse report timeline"],
    outcome: "reinstated", timeToResolveDays: 5, tags: ["bombing", "competitor"] },
  { category: "Review Manipulation", marketplace: "Amazon", title: "Family member left 5-star review",
    summary: "Family member sharing a household account triggered manipulation flag.",
    rootCause: "Shared shipping/IP signals between seller and reviewer.",
    correctiveActions: ["Removed offending review", "Wrote attestation explaining household link"],
    preventiveActions: ["Educated family on marketplace policy", "Separated business shipping address"],
    documents: ["Household attestation", "Address-change evidence"],
    outcome: "reinstated", timeToResolveDays: 7, tags: ["household"] },
  { category: "Review Manipulation", marketplace: "Amazon", title: "Insert-card asking for 5 stars",
    summary: "Product insert card with 'Please leave 5 stars' triggered enforcement.",
    rootCause: "Outdated insert design carried prohibited language.",
    correctiveActions: ["Reprinted compliant insert", "Recalled non-compliant batches from FBA"],
    preventiveActions: ["Legal review on every printed insert"],
    documents: ["Old vs new insert", "Recall order"],
    outcome: "reinstated", timeToResolveDays: 12, tags: ["insert-card"] },
  { category: "Review Manipulation", marketplace: "Amazon", title: "Refund-for-review DM by VA",
    summary: "Virtual assistant offered refunds via Amazon Buyer-Seller Messages.",
    rootCause: "VA was incentivized on review counts.",
    correctiveActions: ["Replaced VA", "Audited 12 months of buyer messages"],
    preventiveActions: ["Removed review metrics from VA compensation"],
    documents: ["Buyer-Seller message export", "VA contract change"],
    outcome: "reinstated", timeToResolveDays: 19, tags: ["VA", "refund-for-review"] },
  { category: "Review Manipulation", marketplace: "Amazon", title: "External review service appeared in plan-of-action audit",
    summary: "Account flagged after seller signed up for a third-party review aggregator.",
    rootCause: "Aggregator service used non-compliant outreach.",
    correctiveActions: ["Cancelled service and obtained written confirmation", "Submitted audit log to Amazon"],
    preventiveActions: ["Vendor compliance review before signup"],
    documents: ["Cancellation confirmation", "Vendor compliance checklist"],
    outcome: "reinstated", timeToResolveDays: 14, tags: ["third-party"] },
  { category: "Review Manipulation", marketplace: "Amazon", title: "Same review text across multiple ASINs",
    summary: "Identical review text appeared across 8 ASINs in 4 days.",
    rootCause: "Buyer was farming reviews; not the seller's doing.",
    correctiveActions: ["Reported buyer", "Showed no relationship via order history audit"],
    preventiveActions: ["Subscribed to review-pattern monitoring tool"],
    documents: ["Order history", "Buyer report ID"],
    outcome: "reinstated", timeToResolveDays: 8, tags: ["pattern"] },

  // ─── Related Account (6) ─────────────────────────────────────────
  { category: "Related Account", marketplace: "Amazon", title: "Related account suspension after office WiFi overlap",
    summary: "Two separate sellers in same coworking space flagged as related.",
    rootCause: "Shared public IP with another suspended account.",
    correctiveActions: ["Switched to dedicated internet line", "Provided utility bill and lease"],
    preventiveActions: ["Use only dedicated network for Seller Central"],
    documents: ["Lease", "ISP bill", "Static IP confirmation"],
    outcome: "reinstated", timeToResolveDays: 11, tags: ["wifi", "coworking"] },
  { category: "Related Account", marketplace: "Amazon", title: "Family member also sells on Amazon",
    summary: "Spouse's separate seller account triggered relation flag.",
    rootCause: "Same home address used on both accounts.",
    correctiveActions: ["Submitted explanation with marriage certificate", "Separated business addresses"],
    preventiveActions: ["Distinct legal addresses per business"],
    documents: ["Marriage certificate", "Business address change letter"],
    outcome: "reinstated", timeToResolveDays: 9, tags: ["family", "address"] },
  { category: "Related Account", marketplace: "Amazon", title: "Acquired a business with prior suspension history",
    summary: "Newly purchased seller account inherited unresolved violations.",
    rootCause: "Acquisition due diligence missed prior enforcement actions.",
    correctiveActions: ["Disclosed acquisition and submitted purchase agreement", "Resolved inherited violations one by one"],
    preventiveActions: ["Account-health review during M&A due diligence"],
    documents: ["Purchase agreement", "Resolution evidence per violation"],
    outcome: "partial", timeToResolveDays: 38, tags: ["m&a"] },
  { category: "Related Account", marketplace: "Amazon", title: "Former employee opened competing account",
    summary: "Ex-employee's new account linked via prior shared login.",
    rootCause: "Did not rotate Seller Central credentials after employee left.",
    correctiveActions: ["Rotated all credentials", "Provided HR offboarding record"],
    preventiveActions: ["Credential rotation on offboarding"],
    documents: ["HR record", "Credential rotation log"],
    outcome: "reinstated", timeToResolveDays: 12, tags: ["offboarding"] },
  { category: "Related Account", marketplace: "Amazon", title: "Browser cookie related-account flag",
    summary: "Used same computer to log into a friend's account once; flagged 6 months later.",
    rootCause: "Browser cookies linked the two sessions.",
    correctiveActions: ["Provided narrative + access timeline", "Switched to separate devices"],
    preventiveActions: ["Dedicated device per Seller Central account"],
    documents: ["Narrative letter", "Device purchase receipt"],
    outcome: "reinstated", timeToResolveDays: 14, tags: ["cookies"] },
  { category: "Related Account", marketplace: "Walmart", title: "Walmart related-account hold after multi-store setup",
    summary: "Opened second store for B2B catalog; flagged as duplicate.",
    rootCause: "Walmart requires explicit approval for related stores.",
    correctiveActions: ["Submitted approval request with B2B/B2C separation explanation"],
    preventiveActions: ["Pre-approval before multi-store rollout"],
    documents: ["Separation memo", "EIN documentation"],
    outcome: "reinstated", timeToResolveDays: 7, tags: ["multi-store"] },

  // ─── Late Shipment (7) ────────────────────────────────────────────
  { category: "Late Shipment", marketplace: "Amazon", title: "LSR breached after carrier strike",
    summary: "Late Shipment Rate climbed to 9% during regional carrier strike.",
    rootCause: "Single-carrier dependency; no contingency.",
    correctiveActions: ["Activated backup carrier accounts", "Issued buyer notifications proactively"],
    preventiveActions: ["Always maintain 2 active carrier contracts"],
    documents: ["New carrier setup", "Buyer notification log"],
    outcome: "reinstated", timeToResolveDays: 21, tags: ["carrier", "strike"] },
  { category: "Late Shipment", marketplace: "Amazon", title: "Handling-time misconfiguration after migration",
    summary: "Bulk listing import reset handling time to 0 days.",
    rootCause: "Catalog feed defaulted to 0-day handling.",
    correctiveActions: ["Restored handling time", "Submitted POA with feed audit"],
    preventiveActions: ["Pre-flight checklist on feed deploys"],
    documents: ["Feed change history", "POA"],
    outcome: "reinstated", timeToResolveDays: 4, tags: ["handling-time", "feed"] },
  { category: "Late Shipment", marketplace: "Amazon", title: "Confirmation timing — confirmed after cutoff",
    summary: "Shipments were confirmed after carrier pickup cutoff, breaching SLA.",
    rootCause: "Warehouse confirmed after labels were printed instead of at handoff.",
    correctiveActions: ["Moved confirmation step to handoff scan"],
    preventiveActions: ["Scan-to-confirm SOP"],
    documents: ["Old vs new SOP", "Sample scan log"],
    outcome: "reinstated", timeToResolveDays: 5, tags: ["SOP"] },
  { category: "Late Shipment", marketplace: "Amazon", title: "Holiday volume blew capacity",
    summary: "Black Friday volume tripled and LSR breached threshold.",
    rootCause: "Capacity planning didn't account for Q4 ramp.",
    correctiveActions: ["Hired seasonal staff", "Increased handling time temporarily"],
    preventiveActions: ["Annual capacity model and staffing plan"],
    documents: ["Staffing schedule", "Updated handling time evidence"],
    outcome: "reinstated", timeToResolveDays: 9, tags: ["seasonal"] },
  { category: "Late Shipment", marketplace: "Walmart", title: "Walmart on-time delivery rate suspension",
    summary: "OTDR dropped below 95% threshold for 4 weeks.",
    rootCause: "Walmart calculates by delivery, not ship — slow carriers hurt metric.",
    correctiveActions: ["Switched to faster carrier in affected zones", "Submitted improvement plan"],
    preventiveActions: ["Carrier scorecard by zone"],
    documents: ["Carrier comparison data", "Improvement plan"],
    outcome: "reinstated", timeToResolveDays: 18, tags: ["walmart", "OTDR"] },
  { category: "Late Shipment", marketplace: "Amazon", title: "Buy Shipping not used — lost on-time protection",
    summary: "External labels caused on-time protection to be voided.",
    rootCause: "Operations used Stamps.com labels outside Buy Shipping.",
    correctiveActions: ["Switched to Buy Shipping for all SFP orders"],
    preventiveActions: ["Buy-Shipping-only policy"],
    documents: ["Shipping policy memo"],
    outcome: "reinstated", timeToResolveDays: 6, tags: ["buy-shipping", "SFP"] },
  { category: "Late Shipment", marketplace: "Amazon", title: "Tracking valid rate dipped after carrier API change",
    summary: "Carrier changed tracking API; events stopped flowing to Amazon.",
    rootCause: "Tracking integration didn't refresh after carrier deployed v2 API.",
    correctiveActions: ["Updated tracking integration", "Manually pushed past events"],
    preventiveActions: ["Monitoring on tracking-event ingestion rate"],
    documents: ["Integration update PR", "Monitoring dashboard screenshot"],
    outcome: "reinstated", timeToResolveDays: 7, tags: ["tracking"] },

  // ─── Restricted Product (5) ──────────────────────────────────────
  { category: "Restricted Product", marketplace: "Amazon", title: "Restricted product — pesticide label",
    summary: "Listing flagged after compliance team scanned for EPA-regulated terms.",
    rootCause: "Product description used regulated 'kills' / 'repels' language.",
    correctiveActions: ["Rewrote description without regulated claims", "Obtained EPA registration for product line"],
    preventiveActions: ["Compliance review for all product copy"],
    documents: ["EPA registration", "Edited listing copy"],
    outcome: "reinstated", timeToResolveDays: 22, tags: ["EPA", "compliance"] },
  { category: "Restricted Product", marketplace: "Amazon", title: "Medical-device claim on consumer product",
    summary: "Massage product claimed to treat a medical condition.",
    rootCause: "Marketing copywriter used FDA-regulated claims.",
    correctiveActions: ["Removed medical claims from all listings", "Issued POA with copywriter retraining plan"],
    preventiveActions: ["FDA claim blocklist applied at publish"],
    documents: ["Blocklist doc", "Training records"],
    outcome: "reinstated", timeToResolveDays: 11, tags: ["FDA", "claims"] },
  { category: "Restricted Product", marketplace: "Amazon", title: "Hazmat misclassification",
    summary: "Lithium battery product wasn't declared hazmat.",
    rootCause: "Supplier didn't disclose battery in product spec sheet.",
    correctiveActions: ["Submitted hazmat review form", "Got new spec sheet from supplier"],
    preventiveActions: ["Hazmat checklist at SKU intake"],
    documents: ["Hazmat review form", "Supplier spec sheet"],
    outcome: "reinstated", timeToResolveDays: 25, tags: ["hazmat", "battery"] },
  { category: "Restricted Product", marketplace: "Walmart", title: "Walmart restricted brand list update",
    summary: "Walmart added brand to restricted list; existing listings disabled.",
    rootCause: "No notification before policy change.",
    correctiveActions: ["Sunset affected SKUs", "Diverted inventory to other channels"],
    preventiveActions: ["Subscribe to Walmart policy bulletin"],
    documents: ["Policy bulletin", "Channel migration plan"],
    outcome: "partial", timeToResolveDays: 30, tags: ["walmart", "policy"] },
  { category: "Restricted Product", marketplace: "Amazon", title: "Glass bottle ban for FBA storage",
    summary: "FBA tightened glass-packaging rules; inventory removed.",
    rootCause: "Did not track FBA packaging policy updates.",
    correctiveActions: ["Repackaged inventory in PET bottles", "Submitted FBA prep guidelines acknowledgment"],
    preventiveActions: ["Quarterly FBA policy review"],
    documents: ["Repackaging photos", "FBA prep guidelines acknowledgment"],
    outcome: "reinstated", timeToResolveDays: 19, tags: ["FBA", "packaging"] },

  // ─── Verification (5) ────────────────────────────────────────────
  { category: "Verification", marketplace: "Amazon", title: "Address verification — utility bill rejected",
    summary: "Verification stalled because utility bill was 92 days old.",
    rootCause: "Submitted slightly out-of-window document.",
    correctiveActions: ["Submitted bank statement under 60 days old"],
    preventiveActions: ["Verification doc bundle refreshed monthly"],
    documents: ["Bank statement", "Verification queue ID"],
    outcome: "reinstated", timeToResolveDays: 4, tags: ["KYC", "utility"] },
  { category: "Verification", marketplace: "Amazon", title: "Beneficial owner change unreported",
    summary: "Equity round added new beneficial owner; verification re-triggered.",
    rootCause: "Did not update Seller Central within 30 days.",
    correctiveActions: ["Updated beneficial owner records", "Submitted updated cap table"],
    preventiveActions: ["Legal triggers Seller Central update on equity events"],
    documents: ["Cap table", "Board resolution"],
    outcome: "reinstated", timeToResolveDays: 8, tags: ["KYC", "equity"] },
  { category: "Verification", marketplace: "Amazon", title: "Bank account country mismatch",
    summary: "Bank account country did not match marketplace region.",
    rootCause: "Used UK bank account on Amazon.com Seller Central.",
    correctiveActions: ["Opened US bank account", "Resubmitted bank verification"],
    preventiveActions: ["Region-correct banking from day one"],
    documents: ["New bank confirmation", "Verification queue ID"],
    outcome: "reinstated", timeToResolveDays: 11, tags: ["banking", "region"] },
  { category: "Verification", marketplace: "Amazon", title: "Video call verification missed",
    summary: "Seller missed scheduled video verification call; account paused.",
    rootCause: "Calendar invite went to spam.",
    correctiveActions: ["Rescheduled call", "Set up dedicated verification mailbox"],
    preventiveActions: ["Verification mailbox monitored daily"],
    documents: ["Verification confirmation email"],
    outcome: "reinstated", timeToResolveDays: 3, tags: ["video-call"] },
  { category: "Verification", marketplace: "Walmart", title: "Walmart W-9 mismatch",
    summary: "Legal name on W-9 didn't match Walmart Seller Center account.",
    rootCause: "DBA name was used on Walmart instead of legal entity.",
    correctiveActions: ["Updated Walmart account to legal entity name"],
    preventiveActions: ["Use legal entity name on all marketplaces"],
    documents: ["Updated W-9", "Account name change confirmation"],
    outcome: "reinstated", timeToResolveDays: 6, tags: ["walmart", "tax"] },
];

export const APPEALS_LIBRARY: AppealCase[] = CASES_RAW.map((c, i) => ({
  ...c,
  id: `case-${String(i + 1).padStart(3, "0")}`,
}));

export const APPEAL_CATEGORIES: AppealCategory[] = [
  "IP Complaint",
  "Inauthentic",
  "Review Manipulation",
  "Related Account",
  "Late Shipment",
  "Restricted Product",
  "Verification",
];

export function appealsByCategory(cat: AppealCategory): AppealCase[] {
  return APPEALS_LIBRARY.filter((c) => c.category === cat);
}

export function appealStats() {
  const total = APPEALS_LIBRARY.length;
  const reinstated = APPEALS_LIBRARY.filter((c) => c.outcome === "reinstated").length;
  const avgDays = Math.round(
    APPEALS_LIBRARY.reduce((s, c) => s + c.timeToResolveDays, 0) / total
  );
  return { total, reinstated, reinstateRate: reinstated / total, avgDays };
}