/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspensionPreventionRouteImport } from './routes/suspension-prevention'
import { Route as HealthCheckRouteImport } from './routes/health-check'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'

const SuspensionPreventionRoute = SuspensionPreventionRouteImport.update({
  id: '/suspension-prevention',
  path: '/suspension-prevention',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthCheckRoute = HealthCheckRouteImport.update({
  id: '/health-check',
  path: '/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/health-check': typeof HealthCheckRoute
  '/suspension-prevention': typeof SuspensionPreventionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/health-check': typeof HealthCheckRoute
  '/suspension-prevention': typeof SuspensionPreventionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/health-check': typeof HealthCheckRoute
  '/suspension-prevention': typeof SuspensionPreventionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calculator' | '/health-check' | '/suspension-prevention'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculator' | '/health-check' | '/suspension-prevention'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/health-check'
    | '/suspension-prevention'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  HealthCheckRoute: typeof HealthCheckRoute
  SuspensionPreventionRoute: typeof SuspensionPreventionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspension-prevention': {
      id: '/suspension-prevention'
      path: '/suspension-prevention'
      fullPath: '/suspension-prevention'
      preLoaderRoute: typeof SuspensionPreventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-check': {
      id: '/health-check'
      path: '/health-check'
      fullPath: '/health-check'
      preLoaderRoute: typeof HealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  HealthCheckRoute: HealthCheckRoute,
  SuspensionPreventionRoute: SuspensionPreventionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
