/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspensionPreventionRouteImport } from './routes/suspension-prevention'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RateCardRouteImport } from './routes/rate-card'
import { Route as PolicyChangesRouteImport } from './routes/policy-changes'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImpactReportsRouteImport } from './routes/impact-reports'
import { Route as HealthCheckRouteImport } from './routes/health-check'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogSlugRouteImport } from './routes/changelog.$slug'
import { Route as ApiPublicPolicyChangesRouteImport } from './routes/api/public/policy-changes'
import { Route as ApiPublicMarketplacesRouteImport } from './routes/api/public/marketplaces'
import { Route as ApiPublicFeesRouteImport } from './routes/api/public/fees'
import { Route as ApiPublicFeeChangesRouteImport } from './routes/api/public/fee-changes'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'

const SuspensionPreventionRoute = SuspensionPreventionRouteImport.update({
  id: '/suspension-prevention',
  path: '/suspension-prevention',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCardRoute = RateCardRouteImport.update({
  id: '/rate-card',
  path: '/rate-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyChangesRoute = PolicyChangesRouteImport.update({
  id: '/policy-changes',
  path: '/policy-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactReportsRoute = ImpactReportsRouteImport.update({
  id: '/impact-reports',
  path: '/impact-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthCheckRoute = HealthCheckRouteImport.update({
  id: '/health-check',
  path: '/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPolicyChangesRoute = ApiPublicPolicyChangesRouteImport.update({
  id: '/api/public/policy-changes',
  path: '/api/public/policy-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketplacesRoute = ApiPublicMarketplacesRouteImport.update({
  id: '/api/public/marketplaces',
  path: '/api/public/marketplaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeesRoute = ApiPublicFeesRouteImport.update({
  id: '/api/public/fees',
  path: '/api/public/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeeChangesRoute = ApiPublicFeeChangesRouteImport.update({
  id: '/api/public/fee-changes',
  path: '/api/public/fee-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/admin/subscribers',
    path: '/admin/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/fees': typeof FeesRoute
  '/health-check': typeof HealthCheckRoute
  '/impact-reports': typeof ImpactReportsRoute
  '/insights': typeof InsightsRoute
  '/methodology': typeof MethodologyRoute
  '/policy-changes': typeof PolicyChangesRoute
  '/rate-card': typeof RateCardRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspension-prevention': typeof SuspensionPreventionRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/fee-changes': typeof ApiPublicFeeChangesRoute
  '/api/public/fees': typeof ApiPublicFeesRoute
  '/api/public/marketplaces': typeof ApiPublicMarketplacesRoute
  '/api/public/policy-changes': typeof ApiPublicPolicyChangesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/fees': typeof FeesRoute
  '/health-check': typeof HealthCheckRoute
  '/impact-reports': typeof ImpactReportsRoute
  '/insights': typeof InsightsRoute
  '/methodology': typeof MethodologyRoute
  '/policy-changes': typeof PolicyChangesRoute
  '/rate-card': typeof RateCardRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspension-prevention': typeof SuspensionPreventionRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/fee-changes': typeof ApiPublicFeeChangesRoute
  '/api/public/fees': typeof ApiPublicFeesRoute
  '/api/public/marketplaces': typeof ApiPublicMarketplacesRoute
  '/api/public/policy-changes': typeof ApiPublicPolicyChangesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/fees': typeof FeesRoute
  '/health-check': typeof HealthCheckRoute
  '/impact-reports': typeof ImpactReportsRoute
  '/insights': typeof InsightsRoute
  '/methodology': typeof MethodologyRoute
  '/policy-changes': typeof PolicyChangesRoute
  '/rate-card': typeof RateCardRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspension-prevention': typeof SuspensionPreventionRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/fee-changes': typeof ApiPublicFeeChangesRoute
  '/api/public/fees': typeof ApiPublicFeesRoute
  '/api/public/marketplaces': typeof ApiPublicMarketplacesRoute
  '/api/public/policy-changes': typeof ApiPublicPolicyChangesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/fees'
    | '/health-check'
    | '/impact-reports'
    | '/insights'
    | '/methodology'
    | '/policy-changes'
    | '/rate-card'
    | '/resources'
    | '/sitemap.xml'
    | '/suspension-prevention'
    | '/changelog/$slug'
    | '/admin/subscribers'
    | '/api/public/fee-changes'
    | '/api/public/fees'
    | '/api/public/marketplaces'
    | '/api/public/policy-changes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/fees'
    | '/health-check'
    | '/impact-reports'
    | '/insights'
    | '/methodology'
    | '/policy-changes'
    | '/rate-card'
    | '/resources'
    | '/sitemap.xml'
    | '/suspension-prevention'
    | '/changelog/$slug'
    | '/admin/subscribers'
    | '/api/public/fee-changes'
    | '/api/public/fees'
    | '/api/public/marketplaces'
    | '/api/public/policy-changes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/fees'
    | '/health-check'
    | '/impact-reports'
    | '/insights'
    | '/methodology'
    | '/policy-changes'
    | '/rate-card'
    | '/resources'
    | '/sitemap.xml'
    | '/suspension-prevention'
    | '/changelog/$slug'
    | '/_authenticated/admin/subscribers'
    | '/api/public/fee-changes'
    | '/api/public/fees'
    | '/api/public/marketplaces'
    | '/api/public/policy-changes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  FeesRoute: typeof FeesRoute
  HealthCheckRoute: typeof HealthCheckRoute
  ImpactReportsRoute: typeof ImpactReportsRoute
  InsightsRoute: typeof InsightsRoute
  MethodologyRoute: typeof MethodologyRoute
  PolicyChangesRoute: typeof PolicyChangesRoute
  RateCardRoute: typeof RateCardRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuspensionPreventionRoute: typeof SuspensionPreventionRoute
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  ApiPublicFeeChangesRoute: typeof ApiPublicFeeChangesRoute
  ApiPublicFeesRoute: typeof ApiPublicFeesRoute
  ApiPublicMarketplacesRoute: typeof ApiPublicMarketplacesRoute
  ApiPublicPolicyChangesRoute: typeof ApiPublicPolicyChangesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspension-prevention': {
      id: '/suspension-prevention'
      path: '/suspension-prevention'
      fullPath: '/suspension-prevention'
      preLoaderRoute: typeof SuspensionPreventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-card': {
      id: '/rate-card'
      path: '/rate-card'
      fullPath: '/rate-card'
      preLoaderRoute: typeof RateCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-changes': {
      id: '/policy-changes'
      path: '/policy-changes'
      fullPath: '/policy-changes'
      preLoaderRoute: typeof PolicyChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-reports': {
      id: '/impact-reports'
      path: '/impact-reports'
      fullPath: '/impact-reports'
      preLoaderRoute: typeof ImpactReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-check': {
      id: '/health-check'
      path: '/health-check'
      fullPath: '/health-check'
      preLoaderRoute: typeof HealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/policy-changes': {
      id: '/api/public/policy-changes'
      path: '/api/public/policy-changes'
      fullPath: '/api/public/policy-changes'
      preLoaderRoute: typeof ApiPublicPolicyChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketplaces': {
      id: '/api/public/marketplaces'
      path: '/api/public/marketplaces'
      fullPath: '/api/public/marketplaces'
      preLoaderRoute: typeof ApiPublicMarketplacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fees': {
      id: '/api/public/fees'
      path: '/api/public/fees'
      fullPath: '/api/public/fees'
      preLoaderRoute: typeof ApiPublicFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fee-changes': {
      id: '/api/public/fee-changes'
      path: '/api/public/fee-changes'
      fullPath: '/api/public/fee-changes'
      preLoaderRoute: typeof ApiPublicFeeChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  FeesRoute: FeesRoute,
  HealthCheckRoute: HealthCheckRoute,
  ImpactReportsRoute: ImpactReportsRoute,
  InsightsRoute: InsightsRoute,
  MethodologyRoute: MethodologyRoute,
  PolicyChangesRoute: PolicyChangesRoute,
  RateCardRoute: RateCardRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuspensionPreventionRoute: SuspensionPreventionRoute,
  ChangelogSlugRoute: ChangelogSlugRoute,
  ApiPublicFeeChangesRoute: ApiPublicFeeChangesRoute,
  ApiPublicFeesRoute: ApiPublicFeesRoute,
  ApiPublicMarketplacesRoute: ApiPublicMarketplacesRoute,
  ApiPublicPolicyChangesRoute: ApiPublicPolicyChangesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
